#!/usr/bin/env python3
"""
Calculates the summation of integers from 2 to 5.
"""


def sigma_sum():
    """
    Returns the sum of integers from 2 to 5.
    """
    return sum(range(2, 6))


if __name__ == "__main__":
    print(sigma_sum())

